feat(ci): get docker image version from git tag
Signed-off-by: Paul Thuriot <pth@corti.ai>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -188,7 +188,6 @@ jobs:
 
       - name: Create release
         uses: docker://ghcr.io/codfish/semantic-release-action:v3
-        id: semantic
         with:
           repository-url: https://github.com/${{ github.repository }}
           branches: |
@@ -217,6 +216,21 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
 
+        # We get the version from the git tag and not from the semantic-release output,
+        # because if the pipeline fails after a release is created,
+        # on rerun, semantic-release output will be null but we still want build and push a new docker image.
+      - name: Extract version from tag
+        id: extract_version
+        run: |
+          version=${GITHUB_REF#refs/tags/}
+
+          # Make sure we only get one tag and it matches the expected format.
+          if [[ ! "${version}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Tag '${version}' does not match required format."
+            exit 1
+          fi
+          echo "version=${version}" >> $GITHUB_OUTPUT
+
       - name: Build and push Docker image
         uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.180
         with:
@@ -226,5 +240,5 @@ jobs:
           platforms: linux/amd64,linux/arm64
           tags: |
             ghcr.io/${{ github.repository }}/kommodity:latest
-            ghcr.io/${{ github.repository }}/kommodity:${{ steps.semantic.outputs.release-version }}
+            ghcr.io/${{ github.repository }}/kommodity:${{ steps.extract_version.outputs.version }}
             ghcr.io/${{ github.repository }}/kommodity:${{ github.sha }}
